title: Wang Shizhu's Homepage
page-top-title: Wang Shizhu
top-section-bg-text: Civil Engineering × Artificial Intelligence
home-subtitle: Wang Shizhu&ensp;|&ensp;王石竹&ensp;|&ensp;土木为基 · AI为翼
copyright-text: '&copy; Wang Shizhu 2025. All Rights Reserved.'
